<script type="text/javascript">
try{
$(document).ready(function(){$( ".course-2029 #course-toc" ).replaceWith('<div></div>');
$( ".course-2029 #region-main" ).prepend('<div class="area"></div><nav class="main-menu"> <ul><li class="has-subnav"> <a href="#section-1"> <i class="fa fa-laptop fa-2x"></i> <span class="nav-text"> Módulo 1 </span> </a> </li> <li class="has-subnav"> <a href="#section-2"> <i class="fa fa-list fa-2x"></i> <span class="nav-text"> Módulo 2 </span> </a> </li> <li class="has-subnav"> <a href="#section-3"> <i class="fa fa-folder-open fa-2x"></i> <span class="nav-text"> Módulo 3 </span> </a> </li> <li> <a href="#section-4"> <i class="fa fa-bar-chart-o fa-2x"></i> <span class="nav-text"> Módulo 4 </span> </a> </li> <li> <a href="#section-5"> <i class="fa fa-font fa-2x"></i> <span class="nav-text"> Módulo 5 </span> </a> </li> <li> <a href="#section-6"> <i class="fa fa-table fa-2x"></i> <span class="nav-text"> Módulo 6 </span> </a> </li> <li> <a href="#section-7"> <i class="fa fa-map-marker fa-2x"></i> <span class="nav-text"> Módulo 7 </span> </a> </li> <li> <a href="#section-8"> <i class="fa fa-info fa-2x"></i> <span class="nav-text"> Módulo 8 </span> </a> </li> <li> <a href="#section-9"> <i class="fa fa-info fa-2x"></i> <span class="nav-text"> Módulo 9 </span> </a> </li> <li> <a href="#section-10"> <i class="fa fa-info fa-2x"></i> <span class="nav-text"> Módulo 10 </span> </a> </li> <li> <a href="#section-11"> <i class="fa fa-info fa-2x"></i> <span class="nav-text"> Módulo 11 </span> </a> </li> <li> <a href="#section-12"> <i class="fa fa-info fa-2x"></i> <span class="nav-text"> Módulo 12 </span> </a> </li> <li> <a href="#section-13"> <i class="fa fa-info fa-2x"></i> <span class="nav-text"> Módulo 13 </span> </a> </li> <li> <a href="#section-14"> <i class="fa fa-info fa-2x"></i> <span class="nav-text"> Módulo 14 </span> </a> </li> <li> <a href="#section-15"> <i class="fa fa-info fa-2x"></i> <span class="nav-text"> Módulo 15 </span> </a> </li> <li> <a href="#section-16"> <i class="fa fa-info fa-2x"></i> <span class="nav-text"> Módulo 16 </span> </a> </li> <li> <a href="#section-17"> <i class="fa fa-info fa-2x"></i> <span class="nav-text"> Módulo 17 </span> </a> </li> <li> <a href="#section-18"> <i class="fa fa-info fa-2x"></i> <span class="nav-text"> Módulo 18 </span> </a> </li> <li> <a href="#section-19"> <i class="fa fa-info fa-2x"></i> <span class="nav-text"> Módulo 19 </span> </a> </li> <li> <a href="#section-20"> <i class="fa fa-info fa-2x"></i> <span class="nav-text"> Módulo 20 </span> </a> </li> <li> <a href="#section-21"> <i class="fa fa-info fa-2x"></i> <span class="nav-text"> Módulo 21 </span> </a> </li> <li> <a href="#section-22"> <i class="fa fa-info fa-2x"></i> <span class="nav-text"> Módulo 22 </span> </a> </li> <li> <a href="#section-23"> <i class="fa fa-info fa-2x"></i> <span class="nav-text"> Módulo 23 </span> </a> </li> <li> <a href="#section-24"> <i class="fa fa-info fa-2x"></i> <span class="nav-text"> Módulo 24 </span> </a> </li> </ul>  </nav>');

});
}catch(error){}
    
</script>
